version: 2

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - gosec
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gosec:
    excludes:
      - G104 # Audit errors not checked
  goimports:
    local-prefixes: github.com/neilsmahajan/productivity-timer

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - noctx
    # Exclude generated files
    - path: docs/
      linters:
        - all
    - path: _templ\.go
      linters:
        - all
