version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - gosec
    - prealloc

  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable:
        - nilness
        - shadow
    gosec:
      excludes:
        - G104 # Audit errors not checked

  exclusions:
    rules:
      # Exclude some linters from running on tests files
      - path: _test\.go
        linters:
          - gosec
          - noctx
      # Exclude generated files
      - path: docs/
        linters:
          - errcheck
          - govet
          - ineffassign
          - staticcheck
          - unused
          - misspell
          - unconvert
          - bodyclose
          - noctx
          - gosec
          - prealloc
      - path: _templ\.go
        linters:
          - errcheck
          - govet
          - ineffassign
          - staticcheck
          - unused
          - misspell
          - unconvert
          - bodyclose
          - noctx
          - gosec
          - prealloc

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/neilsmahajan/productivity-timer
  exclusions:
    paths:
      - docs/
      - _templ\.go
